<?php echo '<optgroup label="England">
            <option value="Bedfordshire"> Bedfordshire </option>
            <option value="Berkshire"> Berkshire </option>
            <option value="Bristol"> Bristol </option>
            <option value="Buckinghamshire"> Buckinghamshire </option>
            <option value="Cambridgeshire"> Cambridgeshire </option>
            <option value="Cheshire"> Cheshire </option>
            <option value="City of London"> City of London </option>
            <option value="Cornwall"> Cornwall </option>
            <option value="Cumbria"> Cumbria </option>
            <option value="Derbyshire"> Derbyshire </option>
            <option value="Devon"> Devon </option>
            <option value="Dorset"> Dorset </option>
            <option value="Durham"> Durham </option>
            <option value="East Riding of Yorkshire"> East Riding of Yorkshire </option>
            <option value="East Sussex"> East Sussex </option>
            <option value="Essex"> Essex </option>
            <option value="Gloucestershire"> Gloucestershire </option>
            <option value="Greater London"> Greater London </option>
            <option value="Greater Manchester"> Greater Manchester </option>
            <option value="Hampshire"> Hampshire </option>
            <option value="Herefordshire"> Herefordshire </option>
            <option value="Hertfordshire"> Hertfordshire </option>
            <option value="Isle of Wight"> Isle of Wight </option>
            <option value="Kent"> Kent </option>
            <option value="Lancashire"> Lancashire </option>
            <option value="Leicestershire"> Leicestershire </option>
            <option value="Lincolnshire"> Lincolnshire </option>
            <option value="Merseyside"> Merseyside </option>
            <option value="Norfolk"> Norfolk </option>
            <option value="North Yorkshire"> North Yorkshire </option>
            <option value="Northamptonshire"> Northamptonshire </option>
            <option value="Northumberland"> Northumberland </option>
            <option value="Nottinghamshire"> Nottinghamshire </option>
            <option value="Oxfordshire"> Oxfordshire </option>
            <option value="Rutland"> Rutland </option>
            <option value="Shropshire"> Shropshire </option>
            <option value="Somerset"> Somerset </option>
            <option value="South Yorkshire"> South Yorkshire </option>
            <option value="Staffordshire"> Staffordshire </option>
            <option value="Suffolk"> Suffolk </option>
            <option value="Surrey"> Surrey </option>
            <option value="Tyne and Wear"> Tyne and Wear </option>
            <option value="Warwickshire"> Warwickshire </option>
            <option value="West Midlands"> West Midlands </option>
            <option value="West Sussex"> West Sussex </option>
            <option value="West Yorkshire"> West Yorkshire </option>
            <option value="Wiltshire"> Wiltshire </option>
            <option value="Worcestershire"> Worcestershire </option>
          </optgroup>
          <optgroup label="Wales">
            <option value="Anglesey"> Anglesey </option>
            <option value="Brecknockshire"> Brecknockshire </option>
            <option value="Caernarfonshire"> Caernarfonshire </option>
            <option value="Carmarthenshire"> Carmarthenshire </option>
            <option value="Cardiganshire"> Cardiganshire </option>
            <option value="Denbighshire"> Denbighshire </option>
            <option value="Flintshire"> Flintshire </option>
            <option value="Glamorgan"> Glamorgan </option>
            <option value="Merioneth"> Merioneth </option>
            <option value="Monmouthshire"> Monmouthshire </option>
            <option value="Montgomeryshire"> Montgomeryshire </option>
            <option value="Pembrokeshire"> Pembrokeshire </option>
            <option value="Radnorshire"> Radnorshire </option>
          </optgroup>
          <optgroup label="Scotland">

            <option value="Aberdeenshire"> Aberdeenshire </option>
            <option value="Angus"> Angus </option>
            <option value="Argyllshire"> Argyllshire </option>
            <option value="Ayrshire"> Ayrshire </option>
            <option value="Banffshire"> Banffshire </option>
            <option value="Berwickshire"> Berwickshire </option>
            <option value="Buteshire"> Buteshire </option>
            <option value="Cromartyshire"> Cromartyshire </option>
            <option value="Caithness"> Caithness </option>
            <option value="Clackmannanshire"> Clackmannanshire </option>
            <option value="Dumfriesshire"> Dumfriesshire </option>
            <option value="Dunbartonshire"> Dunbartonshire </option>
            <option value="East Lothian"> East Lothian </option>
            <option value="Fife"> Fife </option>
            <option value="Inverness-shire"> Inverness-shire </option>
            <option value="Kincardineshire"> Kincardineshire </option>
            <option value="Kinross"> Kinross </option>
            <option value="Kirkcudbrightshire"> Kirkcudbrightshire </option>
            <option value="Lanarkshire"> Lanarkshire </option>
            <option value="Midlothian"> Midlothian </option>
            <option value="Morayshire"> Morayshire </option>
            <option value="Nairnshire"> Nairnshire </option>
            <option value="Orkney"> Orkney </option>
            <option value="Peeblesshire"> Peeblesshire </option>
            <option value="Perthshire"> Perthshire </option>
            <option value="Renfrewshire"> Renfrewshire </option>
            <option value="Ross-shire"> Ross-shire </option>
            <option value="Roxburghshire"> Roxburghshire </option>
            <option value="Selkirkshire"> Selkirkshire </option>
            <option value="Shetland"> Shetland </option>
            <option value="Stirlingshire"> Stirlingshire </option>
            <option value="Sutherland"> Sutherland </option>
            <option value="West Lothian"> West Lothian </option>
            <option value="Wigtownshire"> Wigtownshire </option>
          </optgroup>
          <optgroup label="Northern Ireland">
            <option value="Antrim"> Antrim </option>
            <option value="Armagh"> Armagh </option>
            <option value="Down"> Down </option>
            <option value="Fermanagh"> Fermanagh </option>
            <option value="Londonderry"> Londonderry </option>
            <option value="Tyrone"> Tyrone </option>
          </optgroup>' ?>